### ISSUE TITLE
Refactoring Cloudtrail Plugin

### ISSUE THREAD

**Issue by jihyungSong** [spaceone-dev/plugin-aws-cloudtrail-mon-datasource#12]
### monitoring Log.list parameter

```
options (dict)
secret_data (dict)
schema
query (dict)
start (datetime)
end (datetime)
sort (dict)
limit (int)
```

* Remove `filter` parameter : filter are incorporated as query parameters.
* Add `query` parameter : Contains `LookupAttributes` for calling Cloudtrail's lookup_event() API.
   Reference Link : https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudtrail.html#CloudTrail.Client.lookup_events
* Query information is obtained from each cloud service. 
   Related Issue: [Add CloudTrail data for monitoring log](https://github.com/spaceone-dev/plugin-aws-ec2-inven-collector/issues/90)

Cloudtrail query for EC2 instances is in the following format.

```json
{
    "data": {
        "cloudtrail": {
            "region_name": "REGION_NAME"
            "LookupAttributes": [
                {"AttributeKey": "ResourceName",  "AttributeValue": "i-xxxxxxxxx"}
            ]  
        }
    }
}
```

**Comment by jihyungSong** [comment]
### Data Source Metadata

```yaml
  plugin_info:
    metadata:
      required_keys:
      - data.cloudtrail
      view:
        table:
          layout:
            name: cloudtrail-table
            options:
              fields:
              - key: event_name
                name: Event Name
                options:
                  layout:
                    name: Event Details
                    options:
                      layout:
                        type: raw
                    type: popup
                  sub_key: event_info
                type: more
              - key: event_time
                name: Event Time
                type: datetime
              - key: username
                name: User Name
                type: text
              - key: event_source
                name: Event Source
                type: text
              - key: resources
                name: Resource Type
                options:
                  delimiter: ', '
                  sub_key: resource_type
                type: list
            type: table
```
